dev.github: [ first-aid ]
/packages: [|``` file-zip-manager-decompiler-cleaner.fzm ```|]
main: [ master ]
master: [~/manifest/pkgs/confirm/]
README: (~/MASTERPIECE.VERSION_CONTROLLER)
ACTION: scanner analysis workspace encoder 
 **echo; first person flight simulator 
 **echo: [HI THERE]
